const sampleData = {
  categories: [
    {
      $id: "cat1",
      $createdAt: "2025-08-01T00:00:00Z",
      name: "Fruits",
      nameHindi: "फल",
      description: "Fresh and organic fruits from local farms",
      imageUrl:  "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354759/fruits_cat_e4l9m3.jpg",
      isActive: true,
      parentCategory: undefined, // Changed from null to undefined
    },
    {
      $id: "cat2",
      $createdAt: "2025-08-01T00:00:00Z",
      name: "Vegetables",
      nameHindi: "सब्जियाँ",
      description: "Freshly harvested organic vegetables",
      imageUrl:"https://res.cloudinary.com/dpppce3ix/image/upload/v1755354759/vegetable_cat_mkm3ov.jpg",
      isActive: true,
      parentCategory: undefined, // Changed from null to undefined
    },
    {
      $id: "cat3",
      $createdAt: "2025-08-01T00:00:00Z",
      name: "Grains",
      nameHindi: "अनाज",
      description: "High-quality grains and cereals",
      imageUrl: "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354757/grains_cat_kwkocb.jpg",
      isActive: true,
      parentCategory: undefined, // Changed from null to undefined
    },
  ],
  farmers: [
    {
      $id: "farmer1",
      $createdAt: "2025-08-01T00:00:00Z",
      name: "Ramesh Yadav",
      phone: "+919876543211",
      email: "ramesh.yadav@example.com",
      farmName: "Yadav Organic Farms",
      street: "789 Rural Path",
      city: "Nashik",
      state: "Maharashtra",
      pincode: "422001",
      profileImage: "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354757/farmer_1_xk7iog.jpg",
      farmImages: [
        "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354756/farm1_1_cizvub.jpg",
        "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354756/farm1_2_adjrpp.jpg",
      ],
      rating: 4.5,
      totalReviews: 10,
      isVerified: true,
    },
    {
      $id: "farmer2",
      $createdAt: "2025-08-01T00:00:00Z",
      name: "Sita Devi",
      phone: "+919123456788",
      email: "sita.devi@example.com",
      farmName: "Devi Agro",
      street: "321 Farm Street",
      city: "Surat",
      state: "Gujarat",
      pincode: "395001",
      profileImage: "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354757/farmer_2_ovboyt.jpg",
      farmImages: [
        "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354756/farm2_1_oc2y2i.jpg",
        "https://res.cloudinary.com/dpppce3ix/image/upload/v1755354757/farm2_2_auuxkl.jpg"
      ],
      rating: 4.2,
      totalReviews: 5,
      isVerified: false,
    },
  ],
  products: [
    {
      $id: "prod1",
      $createdAt: "2025-08-01T00:00:00Z",
      $updatedAt: "2025-08-01T00:00:00Z",
      name: "Organic Apples",
      nameHindi: "जैविक सेब",
      description: "Freshly picked organic apples from Nashik",
      category_name: "Fruits",
      farmer_name: "Ramesh Yadav",
      images: ["https://res.cloudinary.com/dpppce3ix/image/upload/v1755354756/apples_iiuyyp.jpg"],
      price: 150.0,
      minimumQuantity: 5,
      availableQuantity: 100,
      variety: "Kashmiri",
      grade: "A",
      harvestDate: "2025-07-01T00:00:00Z",
      expiryDate: "2025-10-01T00:00:00Z",
      storageConditions: "Cool and dry",
      isOrganic: true,
      city: "Nashik",
      state: "Maharashtra",
      deliveryTimeframe: "2-3 days",
      isAvailable: true,
    },
    {
      $id: "prod2",
      $createdAt: "2025-08-01T00:00:00Z",
      $updatedAt: "2025-08-01T00:00:00Z",
      name: "Basmati Rice",
      nameHindi: "बासमती चावल",
      description: "Premium long-grain basmati rice",
      category_name: "Grains",
      farmer_name: "Sita Devi",
      images: ["https://res.cloudinary.com/dpppce3ix/image/upload/v1755354756/basmati_iy0h50.jpg"],
      price: 80.0,
      minimumQuantity: 10,
      availableQuantity: 500,
      variety: "1121",
      grade: "A",
      harvestDate: "2025-06-15T00:00:00Z",
      expiryDate: "2026-06-15T00:00:00Z",
      storageConditions: "Dry storage",
      isOrganic: false,
      city: "Surat",
      state: "Gujarat",
      deliveryTimeframe: "3-5 days",
      isAvailable: true,
    },
    {
      $id: "prod3",
      $createdAt: "2025-08-01T00:00:00Z",
      $updatedAt: "2025-08-01T00:00:00Z",
      name: "Organic Spinach",
      nameHindi: "जैविक पालक",
      description: "Fresh organic spinach leaves",
      category_name: "Vegetables",
      farmer_name: "Ramesh Yadav",
      images: ["https://res.cloudinary.com/dpppce3ix/image/upload/v1755354757/palak_fknaik.jpg"],
      price: 40.0,
      minimumQuantity: 2,
      availableQuantity: 200,
      variety: "Palak",
      grade: "A",
      harvestDate: "2025-07-20T00:00:00Z",
      expiryDate: "2025-08-20T00:00:00Z",
      storageConditions: "Refrigerated",
      isOrganic: true,
      city: "Nashik",
      state: "Maharashtra",
      deliveryTimeframe: "1-2 days",
      isAvailable: true,
    },
  ]
};

export default sampleData;