const sampleData = {
    categories: [
      {
        name: "Fruits",
        nameHindi: "फल",
        description: "Fresh and organic fruits",
        imageUrl: "https://images.unsplash.com/photo-1610832958506-aa56368176cf",
        isActive: true,
      },
      {
        name: "Vegetables",
        nameHindi: "सब्जियाँ",
        description: "Freshly harvested vegetables",
        imageUrl: "https://images.unsplash.com/photo-1447175008436-054170c2e979",
        isActive: true,
      },
      {
        name: "Grains",
        nameHindi: "अनाज",
        description: "High-quality grains and cereals",
        imageUrl: "https://images.unsplash.com/photo-1603046891748-7f6c7a1c24b0",
        isActive: true,
      },
    ],
    farmers: [
      {
        name: "Ramesh Yadav",
        phone: "+919876543211",
        email: "ramesh.yadav@example.com",
        farmName: "Yadav Organic Farms",
        street: "789 Rural Path",
        city: "Nashik",
        state: "Maharashtra",
        pincode: "422001",
        profileImage: "https://images.unsplash.com/photo-1500595046743-ddf4d3d753fd",
        farmImages: [
          "https://images.unsplash.com/photo-1500595046743-ddf4d3d753fd",
          "https://images.unsplash.com/photo-1500932334442-8761ee4810a7",
        ],
        rating: 4.5,
        totalReviews: 10,
        isVerified: true,
      },
      {
        name: "Sita Devi",
        phone: "+919123456788",
        email: "sita.devi@example.com",
        farmName: "Devi Agro",
        street: "321 Farm Street",
        city: "Surat",
        state: "Gujarat",
        pincode: "395001",
        profileImage: "https://images.unsplash.com/photo-1500595046743-ddf4d3d753fd",
        farmImages: [
          "https://images.unsplash.com/photo-1500932334442-8761ee4810a7",
        ],
        rating: 4.2,
        totalReviews: 5,
        isVerified: false,
      },
    ],
    products: [
      {
        name: "Organic Apples",
        nameHindi: "जैविक सेब",
        description: "Freshly picked organic apples",
        category_name: "Fruits",
        farmer_name: "Ramesh Yadav",
        images: ["https://images.unsplash.com/photo-1560806887-1e4cd0b5cbd6"],
        price: 150.0,
        minimumQuantity: 5,
        availableQuantity: 100,
        variety: "Kashmiri",
        grade: "A",
        harvestDate: "2025-07-01T00:00:00Z",
        expiryDate: "2025-10-01T00:00:00Z",
        storageConditions: "Cool and dry",
        isOrganic: true,
        city: "Nashik",
        state: "Maharashtra",
        deliveryTimeframe: "2-3 days",
        isAvailable: true,
      },
      {
        name: "Basmati Rice",
        nameHindi: "बासमती चावल",
        description: "Premium long-grain basmati rice",
        category_name: "Grains",
        farmer_name: "Sita Devi",
        images: ["https://images.unsplash.com/photo-1603046891748-7f6c7a1c24b0"],
        price: 80.0,
        minimumQuantity: 10,
        availableQuantity: 500,
        variety: "1121",
        grade: "A",
        harvestDate: "2025-06-15T00:00:00Z",
        expiryDate: "2026-06-15T00:00:00Z",
        storageConditions: "Dry storage",
        isOrganic: false,
        city: "Surat",
        state: "Gujarat",
        deliveryTimeframe: "3-5 days",
        isAvailable: true,
      },
      {
        name: "Organic Spinach",
        nameHindi: "जैविक पालक",
        description: "Fresh organic spinach leaves",
        category_name: "Vegetables",
        farmer_name: "Ramesh Yadav",
        images: ["https://images.unsplash.com/photo-1576045057995-568f588f82fb"],
        price: 40.0,
        minimumQuantity: 2,
        availableQuantity: 200,
        variety: "Palak",
        grade: "A",
        harvestDate: "2025-07-20T00:00:00Z",
        expiryDate: "2025-08-20T00:00:00Z",
        storageConditions: "Refrigerated",
        isOrganic: true,
        city: "Nashik",
        state: "Maharashtra",
        deliveryTimeframe: "1-2 days",
        isAvailable: true,
      },
    ],
    orders: [
      {
        buyer_id: "user1", // Replace with actual User.$id
        farmer_name: "Ramesh Yadav",
        product_name: "Organic Apples",
        quantity: 10,
        totalAmount: 1500.0,
        status: "confirmed",
        delivery_street: "123 Farm Road",
        delivery_city: "Pune",
        delivery_state: "Maharashtra",
        delivery_pincode: "411001",
        expectedDeliveryDate: "2025-08-10T00:00:00Z",
        paymentStatus: "paid",
        notes: "Deliver in the morning",
      },
      {
        buyer_id: "user2", // Replace with actual User.$id
        farmer_name: "Sita Devi",
        product_name: "Basmati Rice",
        quantity: 20,
        totalAmount: 1600.0,
        status: "pending",
        delivery_street: "456 Village Lane",
        delivery_city: "Ahmedabad",
        delivery_state: "Gujarat",
        delivery_pincode: "380001",
        expectedDeliveryDate: "2025-08-12T00:00:00Z",
        paymentStatus: "pending",
        notes: "Contact before delivery",
      },
    ],
    messages: [
      {
        sender_id: "user1", // Replace with actual User.$id
        receiver_id: "farmer1", // Will map to Ramesh Yadav
        content: "Can you confirm the delivery date for my apple order?",
        messageType: "text",
        isRead: false,
        order_product_name: "Organic Apples",
      },
      {
        sender_id: "farmer1", // Will map to Ramesh Yadav
        receiver_id: "user1", // Replace with actual User.$id
        content: "Delivery scheduled for August 10th morning.",
        messageType: "text",
        isRead: true,
        order_product_name: "Organic Apples",
      },
    ],
    reviews: [
      {
        buyer_id: "user1", // Replace with actual User.$id
        farmer_name: "Ramesh Yadav",
        product_name: "Organic Apples",
        order_product_name: "Organic Apples",
        rating: 5,
        title: "Excellent Apples",
        comment: "Very fresh and tasty, highly recommend!",
        images: ["https://images.unsplash.com/photo-1560806887-1e4cd0b5cbd6"],
        isVerified: true,
      },
      {
        buyer_id: "user2", // Replace with actual User.$id
        farmer_name: "Sita Devi",
        product_name: "Basmati Rice",
        order_product_name: "Basmati Rice",
        rating: 4,
        title: "Good Quality Rice",
        comment: "Great taste, but delivery took longer than expected.",
        images: [],
        isVerified: false,
      },
    ],
  };
  
  export default sampleData;